/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import java.util.Set;
import javax.swing.JButton;

/**
 *
 * @author Pabuence
 */
public class VentanaP extends javax.swing.JFrame {
    private JButton[][] botones = new JButton[9][9];
    /**
     * Creates new form VentanaP
     */
    public VentanaP() {
        initComponents();
        setLocationRelativeTo(null);
        creacionBotones();
        creacionTablero();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void creacionBotones(){
        int x=0, y=0;
        for(int i=0;i<9;i++){
            for(int j=0;j<9;j++){
                botones[i][j] = new JButton();
                botones[i][j].setBounds(x, y, 50, 50);
                botones[i][j].setText(" ");
                jPanel1.add(botones[i][j]);
                x+=50;
                if(x==450){
                    x=0;
                }
            }
            y+=50;
        }
    }
    private int contador=0;
    private int cadenaNum = 1;
    private int contadorColumnas;
    private void corregirColumnas(int columna, int fila){
        contadorColumnas=0;
        for (int i = 0; i < 9; i++) {
            if (i!=columna) {
                contadorColumnas++;
                if(botones[i][fila].getText()!=" "){
                    if(Integer.parseInt(botones[i][fila].getText())==cadenaNum){
                        contadorColumnas--;
                    }
                }
            }
        }
    }
    private int contadorFilas;
    private void corregirFilas(int columna, int fila){
        contadorFilas=0;
        for (int i = 0; i < 9; i++) {
            if (i!=fila) {
                contadorFilas++;
                if(botones[columna][i].getText()!=" "){
                    if(Integer.parseInt(botones[columna][i].getText())==cadenaNum){
                        contadorFilas--;
                    }
                }
            }
        }
    }
    
    private void colocarNumeroT(int columnasInicio, int filasInicio, int columnasFinal, int filasFinal, int numRandomColumnas, int numRandomFilas){
        do {
            botones[numRandomColumnas][numRandomFilas].setText(" ");
            numRandomColumnas = (int)(Math.random()*(columnasFinal-columnasInicio+1)+columnasInicio);
            numRandomFilas = (int)(Math.random()*(filasFinal-filasInicio+1)+filasInicio);
            while((botones[numRandomColumnas][numRandomFilas].getText()!=" ")){
                numRandomColumnas = (int)(Math.random()*(columnasFinal-columnasInicio+1)+columnasInicio);
                numRandomFilas = (int)(Math.random()*(filasFinal-filasInicio+1)+filasInicio);
               }
            botones[numRandomColumnas][numRandomFilas].setText(Integer.toString(cadenaNum));
            corregirColumnas(numRandomColumnas, numRandomFilas);
            corregirFilas(numRandomColumnas, numRandomFilas);
            contador++;
            System.out.println(contador);
        } while (contadorColumnas!=8||contadorFilas!=8);
    }
        int numRandomColumnas=0;
        int numRandomFilas=0;
    private void creacionTablero(){
        int columnasInicio=0, filasInicio=0, columnasFinal=2, filasFinal=2;
        
        for(int i=0; i<4; i++){
            for(int j=0; j<3; j++){
                for (int k=0; k<3; k++) {
                    colocarNumeroT(columnasInicio, filasInicio, columnasFinal, filasFinal, numRandomColumnas, numRandomFilas);
                    filasInicio+=3;
                    filasFinal+=3;
//                    System.out.println(contador);
//                    contador++;
                }
                filasInicio=0;
                filasFinal=2;
                columnasInicio+=3;
                columnasFinal+=3;
            }
            columnasInicio=0; 
            filasInicio=0; 
            columnasFinal=2;
            filasFinal=2;
            cadenaNum++;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaP().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
